version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: chami99/spicy-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://Weather99:chami1999928@weatherdb.kmumq9l.mongodb.net/?retryWrites=true&w=majority&appName=WeatherDB
    depends_on:
      - mongo

  frontend:
    image: chami99/spicy-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
